name: vocabhub
description: An App to help you build vocabulary.
publish_to: "none"
version: 0.7.8+30

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animations: ^2.0.7
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  feature_discovery: ^0.14.1
  firebase_analytics: ^10.4.4
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_messaging_web: ^3.5.1
  firebase_remote_config: ^3.0.9
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.0.0
  flutter_riverpod: ^2.3.6
  flutter_staggered_grid_view: ^0.6.2
  fluttertoast: ^8.0.9
  go_router: ^7.0.2
  google_fonts: ^4.0.4
  google_sign_in: ^5.4.1
  http: ^0.13.6
  intl: ^0.18.0
  json_annotation: ^4.6.0
  navbar_router: ^0.7.3
  # navbar_router:
  #   path: ../../oss/my_packages/navbar_router
  # url: https://github.com/maheshmnj/navbar_router.git
  package_info_plus: ^4.0.1
  pull_to_refresh: ^2.0.0
  realtime_client: ^0.1.15
  rive: ^0.11.4
  share_plus: ^7.2.1
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
  supabase: ^0.3.6
  url_launcher: ^6.1.8
  uuid: ^3.0.6
  webview_flutter: ^4.2.2
  webview_flutter_web: ^0.2.2+1

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.3.1
  lints: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#F9F9F9"
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/rive/
    - .env
    - shorebird.yaml
    - CHANGELOG.md
