name: vocabhub
description: An App to help you build vocabulary.
publish_to: "none"
version: 0.5.0+13

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animations: ^2.0.7
  cupertino_icons: ^1.0.5
  firebase_analytics: ^10.1.0
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_messaging_web: ^3.5.1
  firebase_remote_config: ^3.0.9
  flutter:
    sdk: flutter
  # flutter_local_notifications: ^12.0.3
  fluttertoast: ^8.0.9
  go_router: ^7.0.2
  google_fonts: ^4.0.4
  google_sign_in: ^5.4.1
  http: ^0.13.6
  intl: ^0.18.0
  json_annotation: ^4.6.0
  navbar_router: ^0.5.5
  # git:
  #   url: https://github.com/maheshmnj/navbar_router.git
  package_info_plus: ^4.0.1
  pull_to_refresh: ^2.0.0
  realtime_client: ^0.1.15
  share_plus: ^4.1.0
  shared_preferences: ^2.0.16
  supabase: ^0.3.6
  url_launcher: ^6.1.8
  uuid: ^3.0.6
  webview_flutter: ^4.2.2
  webview_flutter_web: ^0.2.2+1

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  lints: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - .env
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
